server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
#    nacos:
#      server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: user-service
          uri: lb://127.0.0.1:8081
          predicates:
            - Path=/user/**
        - id: order-service
          uri: lb://127.0.0.1:8088
          predicates:
            - Path=/order/**
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
